// Replay a real sliced G-code in the print timelapse: Bambu Studio, Orca and PrusaSlicer files
// (.gcode) and Bambu's sliced project (.gcode.3mf, which holds Metadata/plate_<n>.gcode).
//
//   parseGcode(text, { printer }) -> Toolpath (same shape as toolpath.js buildToolpath), plus
//                                    meta { slicer, estimate (s, from the header), colours, printer }
//   readGcodeFile(file | Blob | ArrayBuffer | Uint8Array) -> Promise<{ text, name }>
//
// Parsed: G0/G1 (X Y Z E F), G2/G3 arcs (I J, linearised), G90/G91, M82/M83, G92, M204 S
// (acceleration), layer markers (Bambu '; CHANGE_LAYER' + '; Z_HEIGHT:', Orca/Prusa ';LAYER_CHANGE'
// + ';Z:', Cura ';LAYER:'; else a rise in Z with extrusion), features ('; FEATURE:' / ';TYPE:'),
// tool changes (T<n>) and M600 as colour changes. Times come from toolpath.js's motion model and are
// scaled to the slicer's own estimate when the header has one, so the counter matches the slicer.
import { FEATURES, segTime, resolvePrinter, CHANGE_S } from './toolpath.js';

const F = Object.fromEntries(FEATURES.map((n, i) => [n, i]));
const featureOf = s => {
  s = s.toLowerCase();
  if (/outer|external|wall-outer/.test(s)) return F.outer;
  if (/top/.test(s)) return F.top;
  if (/bottom/.test(s)) return F.bottom;
  if (/sparse|^infill|internal infill|^fill|gap/.test(s)) return /gap/.test(s) ? F.solid : F.sparse;
  if (/solid|bridge|ironing/.test(s)) return F.solid;
  if (/inner|perimeter|wall|overhang/.test(s)) return F.inner;
  return F.solid;
};
const DEFAULT_COLOURS = ['#F2F0EA', '#1E1E24', '#C8553D', '#2F6FBA', '#E0B43A', '#3A8F5C'];

/** Parse a G-code text into a Toolpath the film can play. */
export function parseGcode(text, opts = {}) {
  const T0 = performance.now();
  const meta = { slicer: 'G-code', estimate: null, colours: [], printer: null, layerCount: null };
  // header / config comments
  const head = text.slice(0, 200000) + '\n' + text.slice(-120000);
  let m;
  if ((m = head.match(/^; (BambuStudio|OrcaSlicer)[^\n]*/m))) meta.slicer = m[0].slice(2).trim();
  else if ((m = head.match(/generated by (PrusaSlicer|SuperSlicer|OrcaSlicer|Cura_SteamEngine)[^\n]*/i))) meta.slicer = m[0].replace(/^generated by /i, '').trim();
  if ((m = head.match(/total estimated time: *([^;\n]+)/))) meta.estimate = parseDur(m[1]);
  else if ((m = head.match(/estimated printing time \(normal mode\) = *([^\n]+)/))) meta.estimate = parseDur(m[1]);
  else if ((m = head.match(/^;TIME:(\d+)/m))) meta.estimate = +m[1];
  if ((m = head.match(/^; (?:filament_colour|extruder_colour) = *([^\n]+)/m))) meta.colours = m[1].split(/[;,]/).map(s => s.replace(/"/g, '').trim()).filter(s => /^#[0-9a-f]{6}$/i.test(s)).map(s => s.toUpperCase());
  if ((m = head.match(/^; printer_model = *([^\n]+)/m))) meta.printer = m[1].trim();
  if ((m = head.match(/total layer number: *(\d+)/))) meta.layerCount = +m[1];
  let bedArea = null;
  if ((m = head.match(/^; (?:printable_area|bed_shape) = *([^\n]+)/m))) {
    const pts = m[1].split(',').map(p => p.split('x').map(Number));
    if (pts.every(p => p.length === 2 && p.every(Number.isFinite))) bedArea = [Math.max(...pts.map(p => p[0])), Math.max(...pts.map(p => p[1]))];
  }
  let maxZ = null;
  if ((m = head.match(/max_z_height: *([\d.]+)/))) maxZ = +m[1];
  const guess = opts.printer || (meta.printer && /A2L/i.test(meta.printer) ? 'a2l' : /A1 mini/i.test(meta.printer || '') ? 'a1mini' : /A1/i.test(meta.printer || '') ? 'a1'
    : /P1/i.test(meta.printer || '') ? 'p1s' : /X1/i.test(meta.printer || '') ? 'x1c' : /MK4|Prusa/i.test(meta.printer || meta.slicer) ? 'mk4' : 'a2l');
  const printer = resolvePrinter(guess);
  if (bedArea) printer.bed = [bedArea[0], bedArea[1], Math.max(printer.bed[2], maxZ || 0)];

  // moves
  const X = [], Y = [], Z = [], K = [], C = [], E = [], V = [], A = [];   // end point, kind, colour, extruding, speed, accel
  const layerStarts = [], layerZ = [];
  let x = 0, y = 0, z = 0, e = 0, f = 3000, rel = false, relE = false, acc = printer.accel, feat = F.solid, tool = 0;
  let pendingLayer = false, pendingZ = null, lastLayerZ = -Infinity, extraTime = [], fixed = 0;
  const palette = meta.colours.length ? meta.colours.slice() : DEFAULT_COLOURS.slice(0, 2);
  const colourOfTool = t => { while (palette.length <= t) palette.push(DEFAULT_COLOURS[palette.length % DEFAULT_COLOURS.length]); return t; };
  // M600 names no colour: the next one is a contrasting stand-in unless the header lists more filaments
  const m600Colour = t => {
    if (palette.length > t + 1) return t + 1;
    const hex = palette[t] || '#F2F0EA', n = parseInt(hex.slice(1), 16);
    const lum = (0.2126 * (n >> 16 & 255) + 0.7152 * (n >> 8 & 255) + 0.0722 * (n & 255)) / 255;
    palette.push(lum > 0.45 ? '#1E1E24' : '#F2F0EA');
    return palette.length - 1;
  };
  const startLayer = zz => { layerStarts.push(X.length); layerZ.push(zz); lastLayerZ = zz; };
  const push = (nx, ny, nz, extr, kind) => {
    X.push(nx); Y.push(ny); Z.push(nz); K.push(kind); C.push(tool); E.push(extr ? 1 : 0); V.push(f / 60); A.push(acc);
  };
  const marked = /^(; CHANGE_LAYER|;LAYER_CHANGE|;LAYER:)/m.test(text);
  const lines = text.split('\n');
  for (let li = 0; li < lines.length; li++) {
    let s = lines[li];
    if (s.charCodeAt(0) === 59) {   // ';' comment
      if (s.startsWith('; CHANGE_LAYER') || s.startsWith(';LAYER_CHANGE') || s.startsWith(';LAYER:')) pendingLayer = true;
      else if (s.startsWith('; Z_HEIGHT:') || s.startsWith(';Z:')) pendingZ = parseFloat(s.slice(s.indexOf(':') + 1));
      else if (s.startsWith('; FEATURE:') || s.startsWith(';TYPE:')) feat = featureOf(s.slice(s.indexOf(':') + 1).trim());
      continue;
    }
    const sc = s.indexOf(';'); if (sc >= 0) s = s.slice(0, sc);
    s = s.trim(); if (!s) continue;
    const sp = s.split(/\s+/), cmd = sp[0].toUpperCase();
    const arg = k => { for (let i = 1; i < sp.length; i++) if (sp[i][0] === k || sp[i][0] === k.toLowerCase()) return parseFloat(sp[i].slice(1)); return NaN; };
    if (cmd === 'G0' || cmd === 'G1' || cmd === 'G2' || cmd === 'G3') {
      const ax = arg('X'), ay = arg('Y'), az = arg('Z'), ae = arg('E'), af = arg('F');
      if (Number.isFinite(af)) f = af;
      const nx = Number.isFinite(ax) ? (rel ? x + ax : ax) : x, ny = Number.isFinite(ay) ? (rel ? y + ay : ay) : y, nz = Number.isFinite(az) ? (rel ? z + az : az) : z;
      let de = 0;
      if (Number.isFinite(ae)) { de = relE || rel ? ae : ae - e; e = relE || rel ? e + ae : ae; }
      const moves = Math.hypot(nx - x, ny - y) > 1e-6;
      const extr = de > 1e-5 && moves;
      if (marked ? pendingLayer && (extr || pendingZ != null) : extr && nz > lastLayerZ + 0.01) { startLayer(pendingZ ?? nz); pendingLayer = false; pendingZ = null; }
      if (!moves && Math.abs(nz - z) < 1e-6) { if (de) fixed += Math.abs(de) / Math.max(1, f / 60); z = nz; continue; }
      if ((cmd === 'G2' || cmd === 'G3') && moves) {
        const I = arg('I') || 0, J = arg('J') || 0, cx = x + I, cy = y + J, r = Math.hypot(I, J);
        let a0 = Math.atan2(y - cy, x - cx), a1 = Math.atan2(ny - cy, nx - cx);
        if (cmd === 'G3') { while (a1 <= a0) a1 += 2 * Math.PI; } else { while (a1 >= a0) a1 -= 2 * Math.PI; }
        const n = Math.max(2, Math.min(64, Math.ceil(Math.abs(a1 - a0) * r / 0.3)));
        for (let i = 1; i <= n; i++) {
          const a = a0 + (a1 - a0) * i / n, zz = z + (nz - z) * i / n;
          push(i === n ? nx : cx + r * Math.cos(a), i === n ? ny : cy + r * Math.sin(a), zz, extr, extr ? feat : F.travel);
        }
      } else push(nx, ny, nz, extr, extr ? feat : F.travel);
      x = nx; y = ny; z = nz;
    } else if (cmd === 'G90') rel = false;
    else if (cmd === 'G91') rel = true;
    else if (cmd === 'M82') relE = false;
    else if (cmd === 'M83') relE = true;
    else if (cmd === 'G92') { const ae = arg('E'); if (Number.isFinite(ae)) e = ae; }
    else if (cmd === 'M204') { const a = arg('S'); if (a > 0) acc = a; else { const p = arg('P'); if (p > 0) acc = p; } }
    else if (cmd === 'M600') { tool = m600Colour(tool); extraTime.push([X.length, CHANGE_S.manual]); }
    else if (/^T\d+$/.test(cmd)) {
      const t = +cmd.slice(1);
      if (t < 16 && t !== tool) { if (layerStarts.length) { extraTime.push([X.length, CHANGE_S.ams]); } tool = colourOfTool(t); }
    } else if (cmd === 'M109') fixed += 30;
    else if (cmd === 'M190') fixed += 45;
    else if (cmd === 'G28') fixed += 12;
    else if (cmd === 'G29') fixed += 60;
    else if (cmd === 'G4') { const p = arg('P'), s2 = arg('S'); fixed += Number.isFinite(s2) ? s2 : Number.isFinite(p) ? p / 1000 : 0; }
  }
  const n = X.length;
  if (!n) throw new Error('No moves found in this G-code');

  // times: one-move lookahead corner speeds (junction deviation), trapezoids
  const t = new Float64Array(n);
  const scv = printer.scv, kj = scv * scv * (Math.SQRT2 - 1);
  const dir = new Float32Array(2 * n), L = new Float32Array(n);
  let px = X[0], py = Y[0], pz = Z[0];
  for (let i = 0; i < n; i++) {
    const dx = X[i] - (i ? X[i - 1] : px), dy = Y[i] - (i ? Y[i - 1] : py), dz = Z[i] - (i ? Z[i - 1] : pz);
    L[i] = Math.hypot(dx, dy, dz); dir[2 * i] = L[i] ? dx / L[i] : 0; dir[2 * i + 1] = L[i] ? dy / L[i] : 0;
  }
  const vj = new Float32Array(n + 1);
  for (let i = 1; i < n; i++) {
    const cos = -(dir[2 * i - 2] * dir[2 * i] + dir[2 * i - 1] * dir[2 * i + 1]);
    const vmax = Math.min(V[i - 1], V[i]);
    if (cos > 0.9999 || !L[i] || !L[i - 1]) { vj[i] = 0; continue; }
    if (cos < -0.9999) { vj[i] = vmax; continue; }
    const sh = Math.sqrt(0.5 * (1 - cos));
    vj[i] = Math.min(vmax, Math.sqrt(kj * sh / (1 - sh)));
  }
  for (let i = n - 1; i >= 0; i--) vj[i] = Math.min(vj[i], Math.sqrt(vj[i + 1] ** 2 + 2 * A[i] * L[i]));
  for (let i = 0; i < n; i++) vj[i + 1] = Math.min(vj[i + 1], Math.sqrt(vj[i] ** 2 + 2 * A[i] * L[i]));
  const extraAt = new Map(extraTime.map(([i, s]) => [i, s]));
  let clock = 0;
  const changeSpans = [];
  for (let i = 0; i < n; i++) {
    if (extraAt.has(i)) { const c0 = clock; clock += extraAt.get(i); changeSpans.push([i, c0, clock]); }
    clock += segTime(L[i], vj[i], vj[i + 1], V[i], A[i]);
    t[i] = clock;
  }
  // scale to the slicer's estimate (its model knows the firmware); the fixed start costs are in it
  let scale = 1;
  if (meta.estimate && clock > 0) scale = Math.max(0.3, Math.min(3, (meta.estimate - Math.min(fixed, meta.estimate * 0.3)) / clock));
  for (let i = 0; i < n; i++) t[i] *= scale;
  const total = t[n - 1];

  // beads and layers
  const layerOfMove = new Int32Array(n);
  let li = -1;
  for (let i = 0; i < n; i++) { while (li + 1 < layerStarts.length && layerStarts[li + 1] <= i) li++; layerOfMove[i] = Math.max(0, li); }
  let nb = 0; for (let i = 1; i < n; i++) if (E[i]) nb++;
  const bp = new Float32Array(nb * 6), bt = new Float32Array(nb * 2), bc = new Uint8Array(nb), bk = new Uint8Array(nb), bl = new Uint32Array(nb);
  let b = 0;
  const lo = [Infinity, Infinity, Infinity], hi = [-Infinity, -Infinity, -Infinity];
  const layerBead0 = new Int32Array(layerStarts.length + 1).fill(-1);
  for (let i = 1; i < n; i++) {
    if (!E[i]) continue;
    bp.set([X[i - 1], Y[i - 1], Z[i], X[i], Y[i], Z[i]], b * 6);
    bt[2 * b] = t[i - 1]; bt[2 * b + 1] = t[i]; bc[b] = C[i]; bk[b] = K[i]; bl[b] = layerOfMove[i];
    if (layerBead0[bl[b]] < 0) layerBead0[bl[b]] = b;
    if (layerStarts.length && i >= layerStarts[0]) for (const [v, k] of [[X[i], 0], [Y[i], 1], [Z[i], 2]]) { if (v < lo[k]) lo[k] = v; if (v > hi[k]) hi[k] = v; }
    b++;
  }
  const layers = layerStarts.map((m0, k) => {
    const m1 = k + 1 < layerStarts.length ? layerStarts[k + 1] : n;
    let b0 = layerBead0[k]; if (b0 < 0) b0 = k ? -1 : 0;
    return { z: layerZ[k], t0: m0 ? t[m0 - 1] : 0, t1: t[m1 - 1], move0: m0, move1: m1, bead0: b0, bead1: 0, parts: 1 };
  });
  for (let k = 0; k < layers.length; k++) {
    if (layers[k].bead0 < 0) layers[k].bead0 = k ? layers[k - 1].bead1 : 0;
    layers[k].bead1 = k + 1 < layers.length && layerBead0[k + 1] >= 0 ? layerBead0[k + 1] : (k + 1 < layers.length ? layers[k].bead0 : nb);
  }
  const zBase = 0;
  const changes = changeSpans.filter(([i]) => layerStarts.length && i >= layerStarts[0]).map(([i, c0, c1]) => {
    const k = layerOfMove[Math.min(n - 1, i)];
    return { layer: k, z: layerZ[k] ?? Z[i], t0: c0 * scale, t1: c1 * scale, from: palette[C[Math.max(0, i - 1)]], to: palette[C[Math.min(n - 1, i)]] };
  });
  const track = { n, x: Float32Array.from(X), y: Float32Array.from(Y), z: Float32Array.from(Z), t, k: Uint8Array.from(K) };
  const H = layers.length > 2 ? +(layers[2].z - layers[1].z).toFixed(3) : 0.2;
  let extruded = 0; for (let i = 0; i < nb; i++) extruded += Math.hypot(bp[6 * i + 3] - bp[6 * i], bp[6 * i + 4] - bp[6 * i + 1]);
  return {
    layers, beads: { n: nb, p: bp, t: bt, c: bc, k: bk, l: bl }, track, palette, changes, total, printer,
    filament: { name: (head.match(/^; filament_type = *([^\n;]+)/m) || [])[1] || '' },
    layerMm: H > 0 ? H : 0.2, lineMm: 0.42, zBase, box: { lo: [lo[0], lo[1], 0], hi: [hi[0], hi[1], hi[2]] },
    parts: [{ name: 'G-code', color: palette[0] }],
    stats: { layers: layers.length, beads: nb, moves: n, extrudedMm: extruded, ms: performance.now() - T0, scale, fixedS: fixed, colourChanges: changes.length },
    meta, source: 'gcode',
  };
}

function parseDur(s) {
  let t = 0, m;
  const re = /(\d+(?:\.\d+)?)\s*(d|h|m|s)/g;
  while ((m = re.exec(s))) t += +m[1] * { d: 86400, h: 3600, m: 60, s: 1 }[m[2]];
  return t || null;
}

/** Text of a .gcode, or of the first plate inside a .gcode.3mf (zip). */
export async function readGcodeFile(src) {
  const name = src?.name || '';
  const buf = src instanceof ArrayBuffer ? new Uint8Array(src) : src instanceof Uint8Array ? src : new Uint8Array(await src.arrayBuffer());
  if (buf[0] === 0x50 && buf[1] === 0x4b) {
    const entries = zipEntries(buf);
    const e = entries.find(x => /^Metadata\/plate_\d+\.gcode$/i.test(x.name)) || entries.find(x => /\.gcode$/i.test(x.name));
    if (!e) throw new Error('This 3MF has no sliced G-code inside (slice and export it as .gcode.3mf)');
    const data = await zipRead(buf, e);
    return { text: new TextDecoder().decode(data), name: e.name };
  }
  return { text: new TextDecoder().decode(buf), name };
}

function zipEntries(u8) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  let eocd = -1;
  for (let i = u8.length - 22; i >= Math.max(0, u8.length - 65557); i--) if (dv.getUint32(i, true) === 0x06054b50) { eocd = i; break; }
  if (eocd < 0) throw new Error('Not a zip file');
  let cd = dv.getUint32(eocd + 16, true), count = dv.getUint16(eocd + 10, true);
  const out = [];
  // zip64 central directory (big sliced projects)
  if (cd === 0xffffffff || count === 0xffff) {
    const loc = eocd - 20;
    if (loc >= 0 && dv.getUint32(loc, true) === 0x07064b50) {
      const z64 = Number(dv.getBigUint64(loc + 8, true));
      count = Number(dv.getBigUint64(z64 + 32, true)); cd = Number(dv.getBigUint64(z64 + 48, true));
    }
  }
  for (let i = 0, p = cd; i < count && dv.getUint32(p, true) === 0x02014b50; i++) {
    const method = dv.getUint16(p + 10, true);
    let csize = dv.getUint32(p + 20, true), usize = dv.getUint32(p + 24, true);
    const nl = dv.getUint16(p + 28, true), xl = dv.getUint16(p + 30, true), cl = dv.getUint16(p + 32, true);
    let off = dv.getUint32(p + 42, true);
    const name = new TextDecoder().decode(u8.subarray(p + 46, p + 46 + nl));
    // zip64 extra field
    for (let q = p + 46 + nl; q < p + 46 + nl + xl;) {
      const id = dv.getUint16(q, true), sz = dv.getUint16(q + 2, true);
      if (id === 1) {
        let r = q + 4;
        if (usize === 0xffffffff) { usize = Number(dv.getBigUint64(r, true)); r += 8; }
        if (csize === 0xffffffff) { csize = Number(dv.getBigUint64(r, true)); r += 8; }
        if (off === 0xffffffff) { off = Number(dv.getBigUint64(r, true)); }
      }
      q += 4 + sz;
    }
    out.push({ name, method, csize, usize, off });
    p += 46 + nl + xl + cl;
  }
  return out;
}
async function zipRead(u8, e) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  const p = e.off, nl = dv.getUint16(p + 26, true), xl = dv.getUint16(p + 28, true);
  const data = u8.subarray(p + 30 + nl + xl, p + 30 + nl + xl + e.csize);
  if (e.method === 0) return data;
  if (e.method !== 8) throw new Error('Unsupported zip compression ' + e.method);
  const ds = new DecompressionStream('deflate-raw');
  const out = new Response(new Blob([data]).stream().pipeThrough(ds));
  return new Uint8Array(await out.arrayBuffer());
}
